(function(){
'use strict';
if(adminMenus.indexOf('Alertas')<0)adminMenus.splice(1,0,'Alertas');
if(ownerMenus.indexOf('Alertas')<0)ownerMenus.splice(1,0,'Alertas');
if(tenantMenus.indexOf('Alertas')<0)tenantMenus.splice(1,0,'Alertas');

function prioBadge(p){var map={urgente:'red',alta:'red',media:'yellow',baixa:'green'};return '<span class="badge '+(map[p]||'yellow')+'">'+esc((p||'média').charAt(0).toUpperCase()+(p||'média').slice(1))+'</span>'}
async function refreshAlerts(){if(currentRole!=='admin')return;try{await request('/rest/v1/rpc/gerar_alertas_operacionais',{method:'POST',headers:authHeaders(session.access_token),body:'{}'})}catch(e){}}
async function resolveAlert(id){try{await request('/rest/v1/alertas?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:Object.assign(authHeaders(session.access_token),{'Prefer':'return=representation'}),body:JSON.stringify({resolvido:true,resolvido_em:new Date().toISOString()})});alertasPage()}catch(e){alert(e.message)}}
window.resolveAlert=resolveAlert;
async function alertasPage(){var C=E('content');C.innerHTML='<div class="panel">Atualizando alertas...</div>';await refreshAlerts();try{var data=await request('/rest/v1/alertas?select=*&order=resolvido.asc,created_at.desc&limit=200',{headers:authHeaders(session.access_token)});window._alerts=data||[];var ab=(data||[]).filter(function(x){return !x.resolvido}),urg=ab.filter(function(x){return x.prioridade==='urgente'}).length,alta=ab.filter(function(x){return x.prioridade==='alta'}).length;var rows=(data||[]).map(function(a){return '<tr><td>'+prioBadge(a.prioridade)+'</td><td><b>'+esc(a.titulo)+'</b><div class="muted">'+esc(a.mensagem)+'</div></td><td>'+dateBR(a.data_evento)+'</td><td>'+st(a.resolvido?'pago':'pendente')+'</td><td>'+(currentRole==='admin'&&!a.resolvido?'<div class="rowactions"><button onclick="resolveAlert(\''+a.id+'\')">Marcar como resolvido</button></div>':'—')+'</td></tr>'}).join('');C.innerHTML='<div class="cards"><div class="card redish"><div class="cl">Urgentes</div><div class="num">'+urg+'</div></div><div class="card goldish"><div class="cl">Alta prioridade</div><div class="num">'+alta+'</div></div><div class="card blue"><div class="cl">Alertas abertos</div><div class="num">'+ab.length+'</div></div><div class="card greenish"><div class="cl">Resolvidos</div><div class="num">'+((data||[]).length-ab.length)+'</div></div></div><div class="panel"><div class="panel-title"><h3>Central de Alertas</h3></div><p class="muted">Acompanhe vencimentos, atrasos, contratos e documentos que exigem atenção. As formas de notificação serão definidas em uma próxima etapa.</p><div class="tablewrap"><table class="table"><thead><tr><th>Prioridade</th><th>Alerta</th><th>Data</th><th>Situação</th><th>Ações</th></tr></thead><tbody>'+(rows||'<tr><td colspan="5" class="empty">Nenhum alerta no momento.</td></tr>')+'</tbody></table></div></div>'}catch(e){C.innerHTML='<div class="notice err">'+esc(e.message)+'</div>'}}
var oldLoad=window.load;window.load=async function(){if(page==='Alertas')return alertasPage();return oldLoad()};
})();