(function(){
'use strict';

if(adminMenus.indexOf('Repasses')<0){var ai=adminMenus.indexOf('Relatórios');adminMenus.splice(ai>=0?ai:adminMenus.length,0,'Repasses')}
if(ownerMenus.indexOf('Repasses')<0){var oi=ownerMenus.indexOf('Relatórios');ownerMenus.splice(oi>=0?oi:ownerMenus.length,0,'Repasses')}

var oldNavIcon=window.navIcon;
window.navIcon=function(x){if(x==='Repasses')return '↗';return oldNavIcon(x)};

function mesKey(v){return String(v||'').slice(0,7)}
function mesLabel(k){if(!k)return '—';var p=k.split('-'),n=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];return n[Number(p[1])-1]+' de '+p[0]}
function propNome(id){var p=(cache.proprietarios||[]).find(function(x){return x.id===id});return p?p.nome:'Proprietário'}
function brl(v){return money(Number(v||0))}
function escAttr(v){return esc(v).replace(/"/g,'&quot;')}

async function rpc(name,obj){return request('/rest/v1/rpc/'+name,{method:'POST',headers:authHeaders(session.access_token),body:JSON.stringify(obj||{})})}

async function repassesPage(){
 var C=E('content');C.innerHTML='<div class="panel">Carregando repasses...</div>';
 await Promise.all([
   cache.proprietarios?Promise.resolve(cache.proprietarios):dbGet('proprietarios'),
   cache.imoveis?Promise.resolve(cache.imoveis):dbGet('imoveis'),
   cache.cobrancas?Promise.resolve(cache.cobrancas):dbGet('cobrancas'),
   cache.financeiro?Promise.resolve(cache.financeiro):dbGet('financeiro'),
   dbGet('repasses')
 ]);
 var props=cache.proprietarios||[], reps=cache.repasses||[], hoje=new Date(), atual=window._repasseMonth||hoje.toISOString().slice(0,7);window._repasseMonth=atual;
 var meses={};reps.forEach(function(r){meses[mesKey(r.competencia)]=1});meses[atual]=1;
 var opts=Object.keys(meses).sort().reverse().map(function(k){return '<option value="'+k+'" '+(k===atual?'selected':'')+'>'+mesLabel(k)+'</option>'}).join('');
 var rows=reps.filter(function(r){return mesKey(r.competencia)===atual});
 var totalBruto=rows.reduce(function(s,r){return s+Number(r.valor_bruto||0)},0),totalTaxa=rows.reduce(function(s,r){return s+Number(r.taxa_administracao||0)},0),totalDed=rows.reduce(function(s,r){return s+Number(r.outras_deducoes||0)},0),totalLiq=rows.reduce(function(s,r){return s+Number(r.valor_liquido||0)},0);
 var trs=rows.map(function(r){var ac='';if(currentRole==='admin'){if(r.status==='pago')ac='<button class="linkmini" data-open-statement="'+r.proprietario_id+'">Extrato</button><button class="linkmini" data-reopen="'+r.id+'">Reabrir</button>';else ac='<button class="linkmini" data-open-statement="'+r.proprietario_id+'">Extrato</button><button class="btn primary" style="padding:7px 10px" data-pay-rep="'+r.id+'">Efetivar repasse</button>'}else ac='<button class="linkmini" data-open-statement="'+r.proprietario_id+'">Ver extrato</button>';
   return '<tr><td>'+esc(propNome(r.proprietario_id))+'</td><td>'+brl(r.valor_bruto)+'</td><td>'+Number(r.taxa_percentual||0).toLocaleString('pt-BR')+'%</td><td>'+brl(r.taxa_administracao)+'</td><td>'+brl(r.outras_deducoes)+'</td><td><b>'+brl(r.valor_liquido)+'</b></td><td>'+st(r.status)+'</td><td>'+dateBR(r.data_repasse)+'</td><td><div class="rowactions">'+ac+'</div></td></tr>'
 }).join('');
 C.innerHTML='<div class="panel"><div class="toolbar"><div><h3 style="margin:0">Repasses aos proprietários</h3><div class="muted">Recebimentos do mês menos taxa de administração e despesas vinculadas aos imóveis.</div></div><div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center"><input id="repMonth" class="inp" type="month" value="'+atual+'" style="width:auto">'+(currentRole==='admin'?'<button id="genRep" class="btn primary">Gerar / recalcular repasses</button>':'')+'</div></div></div><div class="cards"><div class="card"><div class="cl">Recebido bruto</div><div class="num">'+brl(totalBruto)+'</div></div><div class="card"><div class="cl">Taxa de administração</div><div class="num">'+brl(totalTaxa)+'</div></div><div class="card"><div class="cl">Outras deduções</div><div class="num">'+brl(totalDed)+'</div></div><div class="card"><div class="cl">Líquido a repassar</div><div class="num" style="color:var(--green)">'+brl(totalLiq)+'</div></div></div><div class="panel"><div class="tablewrap"><table class="table"><thead><tr><th>Proprietário</th><th>Bruto</th><th>Taxa</th><th>Administração</th><th>Despesas</th><th>Líquido</th><th>Situação</th><th>Data do repasse</th><th>Ações</th></tr></thead><tbody>'+(trs||'<tr><td colspan="9" class="empty">Nenhum repasse calculado para este mês.</td></tr>')+'</tbody></table></div><div class="notice">O cálculo usa somente cobranças pagas. A taxa aplicada é a definida no cadastro de cada proprietário. Despesas financeiras pagas e vinculadas aos imóveis do proprietário reduzem o valor líquido.</div></div><div id="statementArea"></div>';
 E('repMonth').onchange=function(){window._repasseMonth=this.value;repassesPage()};
 if(E('genRep'))E('genRep').onclick=async function(){var b=this;b.disabled=true;b.textContent='Calculando...';try{var n=await rpc('gerar_repasses_mes',{p_competencia:atual+'-01'});cache.repasses=null;cache.financeiro=null;await repassesPage();alert('Repasses calculados com sucesso. Registros processados: '+n)}catch(e){alert('Não foi possível calcular: '+e.message)}finally{b.disabled=false}};
 Array.prototype.forEach.call(document.querySelectorAll('[data-pay-rep]'),function(b){b.onclick=function(){openPayRep(b.getAttribute('data-pay-rep'))}});
 Array.prototype.forEach.call(document.querySelectorAll('[data-reopen]'),function(b){b.onclick=async function(){if(!confirm('Reabrir este repasse? A saída automática do Financeiro será removida.'))return;await dbUpdate('repasses',b.getAttribute('data-reopen'),{status:'pendente',data_repasse:null});cache.repasses=null;cache.financeiro=null;repassesPage()}});
 Array.prototype.forEach.call(document.querySelectorAll('[data-open-statement]'),function(b){b.onclick=function(){renderStatement(b.getAttribute('data-open-statement'),atual)}});
 if(currentRole==='proprietario'&&rows.length===1)renderStatement(rows[0].proprietario_id,atual);
}

function openPayRep(id){var r=(cache.repasses||[]).find(function(x){return x.id===id});if(!r)return;var today=new Date().toISOString().slice(0,10);document.body.insertAdjacentHTML('beforeend','<div class="modalbg" id="repModal"><div class="modal"><div class="modalhead"><h2>Efetivar repasse</h2><button id="closeRep" class="close">×</button></div><div class="modalbody"><div class="notice"><b>'+esc(propNome(r.proprietario_id))+'</b><br>Valor líquido: <b>'+brl(r.valor_liquido)+'</b></div><span class="lbl">Data do repasse</span><input id="repDate" class="inp" type="date" value="'+today+'"><span class="lbl">Forma de pagamento</span><select id="repPay" class="inp"><option value="pix">PIX</option><option value="transferencia">Transferência</option><option value="dinheiro">Dinheiro</option><option value="outro">Outro</option></select><span class="lbl">Observações</span><textarea id="repObs" class="inp"></textarea></div><div class="modalfoot"><button id="cancelRep" class="btn secondary">Cancelar</button><button id="saveRep" class="btn primary">Confirmar repasse</button></div></div></div>');
 E('closeRep').onclick=E('cancelRep').onclick=function(){E('repModal').remove()};E('saveRep').onclick=async function(){var btn=this;btn.disabled=true;try{await dbUpdate('repasses',id,{status:'pago',data_repasse:E('repDate').value,forma_pagamento:E('repPay').value,observacoes:E('repObs').value||null});E('repModal').remove();cache.repasses=null;cache.financeiro=null;repassesPage()}catch(e){alert('Erro ao efetivar repasse: '+e.message);btn.disabled=false}};
}

function statementData(propId,month){var props=cache.proprietarios||[],ims=(cache.imoveis||[]).filter(function(i){return i.proprietario_id===propId}),ids=ims.map(function(i){return i.id}),cobs=(cache.cobrancas||[]).filter(function(c){return ids.indexOf(c.imovel_id)>=0&&mesKey(c.competencia)===month&&c.status==='pago'}),fins=(cache.financeiro||[]).filter(function(f){return ids.indexOf(f.imovel_id)>=0&&mesKey(f.competencia||f.data)===month&&f.tipo==='despesa'&&f.pago}),rep=(cache.repasses||[]).find(function(r){return r.proprietario_id===propId&&mesKey(r.competencia)===month}),p=props.find(function(x){return x.id===propId});return {p:p,ims:ims,cobs:cobs,fins:fins,rep:rep}}
function statementRows(d){var arr=[];d.cobs.forEach(function(c){var im=d.ims.find(function(i){return i.id===c.imovel_id});arr.push({data:c.data_pagamento||c.vencimento,tipo:'Receita',descricao:'Aluguel recebido — '+(im?im.nome:'Imóvel'),credito:Number(c.valor_pago||0),debito:0})});d.fins.forEach(function(f){var im=d.ims.find(function(i){return i.id===f.imovel_id});arr.push({data:f.data,tipo:'Despesa',descricao:(f.descricao||f.categoria||'Despesa')+' — '+(im?im.nome:'Imóvel'),credito:0,debito:Number(f.saida||0)})});if(d.rep&&Number(d.rep.taxa_administracao)>0)arr.push({data:d.rep.data_repasse||d.rep.competencia,tipo:'Taxa',descricao:'Taxa de administração ('+Number(d.rep.taxa_percentual||0).toLocaleString('pt-BR')+'%)',credito:0,debito:Number(d.rep.taxa_administracao||0)});return arr.sort(function(a,b){return String(a.data).localeCompare(String(b.data))})}
function renderStatement(propId,month){var d=statementData(propId,month),rows=statementRows(d),rep=d.rep,bruto=rep?Number(rep.valor_bruto||0):d.cobs.reduce(function(s,c){return s+Number(c.valor_pago||0)},0),taxa=rep?Number(rep.taxa_administracao||0):0,ded=rep?Number(rep.outras_deducoes||0):d.fins.reduce(function(s,f){return s+Number(f.saida||0)},0),liq=rep?Number(rep.valor_liquido||0):Math.max(0,bruto-taxa-ded);var trs=rows.map(function(x){return '<tr><td>'+dateBR(x.data)+'</td><td>'+esc(x.tipo)+'</td><td>'+esc(x.descricao)+'</td><td>'+ (x.credito?brl(x.credito):'—')+'</td><td>'+ (x.debito?brl(x.debito):'—')+'</td></tr>'}).join('');var A=E('statementArea');if(!A)return;A.innerHTML='<div class="panel" id="ownerStatement"><div class="toolbar"><div><h3 style="margin:0">Extrato mensal do proprietário</h3><div class="muted">'+esc(d.p?d.p.nome:'Proprietário')+' • '+mesLabel(month)+'</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="statementPDF" class="btn secondary">PDF</button><button id="statementExcel" class="btn secondary">Excel</button></div></div><div class="cards"><div class="card"><div class="cl">Receitas</div><div class="num">'+brl(bruto)+'</div></div><div class="card"><div class="cl">Taxa de administração</div><div class="num">'+brl(taxa)+'</div></div><div class="card"><div class="cl">Outras despesas</div><div class="num">'+brl(ded)+'</div></div><div class="card"><div class="cl">Líquido</div><div class="num" style="color:var(--green)">'+brl(liq)+'</div></div></div><div class="tablewrap"><table class="table" id="statementTable"><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Crédito</th><th>Débito</th></tr></thead><tbody>'+(trs||'<tr><td colspan="5" class="empty">Sem movimentações neste mês.</td></tr>')+'</tbody></table></div><div class="notice">Situação do repasse: '+(rep?st(rep.status):'Ainda não calculado')+(rep&&rep.data_repasse?' • realizado em '+dateBR(rep.data_repasse):'')+'.</div></div>';
 E('statementPDF').onclick=function(){exportPDF(d,month,rows,bruto,taxa,ded,liq)};E('statementExcel').onclick=function(){exportExcel(d,month,rows,bruto,taxa,ded,liq)};
}
function exportPDF(d,month,rows,bruto,taxa,ded,liq){var w=window.open('','_blank'),trs=rows.map(function(x){return '<tr><td>'+dateBR(x.data)+'</td><td>'+esc(x.tipo)+'</td><td>'+esc(x.descricao)+'</td><td>'+(x.credito?brl(x.credito):'')+'</td><td>'+(x.debito?brl(x.debito):'')+'</td></tr>'}).join('');w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Extrato '+escAttr(d.p?d.p.nome:'Proprietário')+'</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#17283d}h1{margin-bottom:4px}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{border-bottom:1px solid #ddd;padding:9px;text-align:left}.summary{display:flex;gap:20px;flex-wrap:wrap;margin:20px 0}.box{border:1px solid #ddd;border-radius:8px;padding:12px;min-width:160px}.box b{display:block;font-size:18px;margin-top:5px}@media print{button{display:none}}</style></head><body><h1>Matos, Gestão de Aluguéis</h1><div>Extrato de '+esc(d.p?d.p.nome:'Proprietário')+' — '+mesLabel(month)+'</div><div class="summary"><div class="box">Receitas<b>'+brl(bruto)+'</b></div><div class="box">Taxa administrativa<b>'+brl(taxa)+'</b></div><div class="box">Despesas<b>'+brl(ded)+'</b></div><div class="box">Líquido<b>'+brl(liq)+'</b></div></div><table><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Crédito</th><th>Débito</th></tr></thead><tbody>'+trs+'</tbody></table><script>window.onload=function(){window.print()}<\/script></body></html>');w.document.close()}
function exportExcel(d,month,rows,bruto,taxa,ded,liq){var t='<table><tr><th colspan="5">Matos - Gestão de Aluguéis</th></tr><tr><td colspan="5">Extrato: '+esc(d.p?d.p.nome:'Proprietário')+' - '+mesLabel(month)+'</td></tr><tr><td>Receitas</td><td>'+bruto.toFixed(2)+'</td><td>Taxa administração</td><td>'+taxa.toFixed(2)+'</td></tr><tr><td>Outras despesas</td><td>'+ded.toFixed(2)+'</td><td>Líquido</td><td>'+liq.toFixed(2)+'</td></tr><tr></tr><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Crédito</th><th>Débito</th></tr>'+rows.map(function(x){return '<tr><td>'+dateBR(x.data)+'</td><td>'+esc(x.tipo)+'</td><td>'+esc(x.descricao)+'</td><td>'+Number(x.credito||0).toFixed(2)+'</td><td>'+Number(x.debito||0).toFixed(2)+'</td></tr>'}).join('')+'</table>';var blob=new Blob(['\ufeff<html><head><meta charset="utf-8"></head><body>'+t+'</body></html>'],{type:'application/vnd.ms-excel'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='extrato-'+(d.p?d.p.nome:'proprietario').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'-'+month+'.xls';document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove()},1000)}

var oldLoad=window.load;
window.load=async function(){if(page==='Repasses')return repassesPage();return oldLoad()};
window.repassesPage=repassesPage;
})();
