(function(){
'use strict';
let installPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
window.addEventListener('appinstalled',()=>{installPrompt=null;localStorage.setItem('matos_pwa_installed','1')});
function loadScript(src){return new Promise((ok,fail)=>{if(document.querySelector('script[src="'+src+'"]'))return ok();let s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=fail;document.head.appendChild(s)})}
async function registerSW(){if(!('serviceWorker'in navigator))return null;return navigator.serviceWorker.register('/sw.js?v=2',{scope:'/'})}
async function ensureFirebase(){await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js');if(!firebase.apps.length)firebase.initializeApp(window.MATOS_FIREBASE.config);return firebase.messaging()}
window.installMatosApp=async function(){if(!installPrompt){alert('Abra o menu do navegador e escolha “Instalar aplicativo” ou “Adicionar à tela inicial”.');return}installPrompt.prompt();await installPrompt.userChoice;installPrompt=null};
window.enableRemotePush=async function(){if(!session||!session.user)throw new Error('Faça login antes de ativar as notificações.');if(!window.MATOS_FIREBASE.vapidKey)throw new Error('A chave pública VAPID ainda não foi configurada.');if(!('Notification'in window))throw new Error('Este navegador não oferece notificações web.');let p=await Notification.requestPermission();if(p!=='granted')throw new Error('Permissão de notificações não concedida.');let reg=await registerSW(),messaging=await ensureFirebase();let token=await messaging.getToken({vapidKey:window.MATOS_FIREBASE.vapidKey,serviceWorkerRegistration:reg});if(!token)throw new Error('Não foi possível obter o token deste aparelho.');await request('/rest/v1/push_dispositivos?on_conflict=user_id,endpoint',{method:'POST',headers:Object.assign(authHeaders(session.access_token),{'Prefer':'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify({user_id:session.user.id,endpoint:token,plataforma:navigator.platform||null,navegador:navigator.userAgent||null,ativo:true,ultimo_uso:new Date().toISOString()})});localStorage.setItem('matos_push_token',token);return true};
window.testMatosNotification=async function(){if(Notification.permission!=='granted'){let p=await Notification.requestPermission();if(p!=='granted')throw new Error('Permissão não concedida.')}let reg=await registerSW();await reg.showNotification('Teste – Matos',{body:'As notificações deste aparelho estão funcionando.',tag:'matos-teste',data:{url:'/'}});return true};
registerSW().catch(console.warn);
})();