(function(){
'use strict';
let installPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
window.addEventListener('appinstalled',()=>{installPrompt=null;localStorage.setItem('matos_pwa_installed','1')});
function loadScript(src){return new Promise((ok,fail)=>{if(document.querySelector('script[src="'+src+'"]'))return ok();let s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=fail;document.head.appendChild(s)})}
async function registerSW(force){if(!('serviceWorker'in navigator))return null;if(force){const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs){try{const sub=await r.pushManager.getSubscription();if(sub)await sub.unsubscribe()}catch(_){ }try{await r.unregister()}catch(_){ }}}const reg=await navigator.serviceWorker.register('/sw.js?v=3',{scope:'/'});await navigator.serviceWorker.ready;try{await reg.update()}catch(_){ }return reg}
async function ensureFirebase(){await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');await loadScript('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js');if(!firebase.apps.length)firebase.initializeApp(window.MATOS_FIREBASE.config);return firebase.messaging()}
window.installMatosApp=async function(){if(!installPrompt){alert('Abra o menu do navegador e escolha “Instalar aplicativo” ou “Adicionar à tela inicial”.');return}installPrompt.prompt();await installPrompt.userChoice;installPrompt=null};
window.enableRemotePush=async function(){if(!session||!session.user)throw new Error('Faça login antes de ativar as notificações.');if(!window.MATOS_FIREBASE||!window.MATOS_FIREBASE.vapidKey)throw new Error('A chave pública VAPID não está configurada.');if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Este navegador não oferece suporte completo a notificações push.');let p=Notification.permission;if(p==='default')p=await Notification.requestPermission();if(p!=='granted')throw new Error('Permissão de notificações não concedida.');let reg,messaging,token;try{reg=await registerSW(true);messaging=await ensureFirebase();try{await messaging.deleteToken()}catch(_){ }token=await messaging.getToken({vapidKey:window.MATOS_FIREBASE.vapidKey,serviceWorkerRegistration:reg});}catch(e){const msg=(e&&e.message)||String(e);if(/push service error|registration failed/i.test(msg)){throw new Error('O Chrome autorizou notificações, mas o serviço de push do aparelho recusou o registro. Verifique se o Google Play Services e o Chrome estão atualizados, desative economia extrema de bateria para o Chrome e tente novamente. Detalhe: '+msg)}throw e}if(!token)throw new Error('O Firebase não retornou um token para este aparelho.');await request('/rest/v1/push_dispositivos?on_conflict=user_id,endpoint',{method:'POST',headers:Object.assign(authHeaders(session.access_token),{'Prefer':'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify({user_id:session.user.id,endpoint:token,plataforma:navigator.platform||null,navegador:navigator.userAgent||null,ativo:true,ultimo_uso:new Date().toISOString()})});localStorage.setItem('matos_push_token',token);localStorage.setItem('matos_push_enabled','1');return true};
window.testMatosNotification=async function(){if(Notification.permission!=='granted'){let p=await Notification.requestPermission();if(p!=='granted')throw new Error('Permissão não concedida.')}let reg=await registerSW(false);await reg.showNotification('Teste – Matos',{body:'As notificações locais deste aparelho estão funcionando.',tag:'matos-teste',data:{url:'/'}});return true};
window.resetMatosPush=async function(){try{const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs){const sub=await r.pushManager.getSubscription();if(sub)await sub.unsubscribe();await r.unregister()}}catch(_){ }localStorage.removeItem('matos_push_token');localStorage.removeItem('matos_push_enabled');return true};
registerSW(false).catch(console.warn);
})();